import { UserProfile } from '../domain/types';
import { APP } from '../constants/app';
import { apiFetch } from './client';
import { getToken } from './session';

/** Profile read/update — backend `/users/me`. */

export interface ProfileUpdateBody {
  firstName?: string;
  lastName?: string;
  email?: string;
  city?: string;
  state?: string;
  /** URL of an already-uploaded image. */
  avatar?: string;
}

export const profileApi = {
  me: () => apiFetch<UserProfile>('/users/me'),
  update: (body: ProfileUpdateBody) =>
    apiFetch<UserProfile>('/users/me', { method: 'PATCH', body }),
};

/**
 * Uploads an image and returns its URL.
 *
 * Uses the shared document-upload endpoint (the only upload the API exposes;
 * it accepts any file up to 10 MB and serves it back from /media). This is a
 * multipart request, so it bypasses `apiFetch` — that helper always sets a
 * JSON content-type, and the boundary must be generated by fetch itself.
 */
export async function uploadImage(uri: string, name = 'avatar.jpg'): Promise<string> {
  const form = new FormData();
  // React Native's FormData accepts this file descriptor shape.
  form.append('file', { uri, name, type: 'image/jpeg' } as unknown as Blob);

  const token = await getToken();
  const res = await fetch(`${APP.apiBaseUrl.replace(/\/+$/, '')}/ownership/documents/upload`, {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      // Content-Type is intentionally omitted: fetch adds it with the boundary.
    },
    body: form,
  });

  if (!res.ok) {
    throw new Error(res.status === 413 ? 'Image is too large (max 10MB).' : 'Upload failed.');
  }
  const data = (await res.json()) as { url: string };
  return data.url;
}
