import { APP } from '../constants/app';
import { TicketCategory } from '../domain/types';
import { apiFetch } from './client';
import type {
  TicketDetailDto,
  TicketListDto,
  TicketMessageCreateDto,
} from './dto';
import { getToken } from './session';

/** Customer support endpoints — backend `/support` router. */

/** Server-side cap; mirrored here so we can stop the user before a 422. */
export const MAX_TICKET_ATTACHMENTS = 5;
export const MAX_IMAGE_BYTES = 10 * 1024 * 1024;
export const MAX_ATTACHMENT_BYTES = 50 * 1024 * 1024;
export const MAX_VIDEO_DURATION_SECONDS = 120;

export interface CreateTicketBody {
  category: TicketCategory;
  subject: string;
  /** Opening message. */
  body: string;
  priority?: string;
  /** Media URLs from {@link uploadTicketAttachment}. */
  attachments?: string[];
}

/**
 * Uploads one attachment and returns the URL to send with a ticket or reply.
 *
 * Multipart, so it bypasses `apiFetch` — that helper always sets a JSON
 * content-type, and the boundary has to be generated by fetch itself.
 *
 * The API accepts JPEG/PNG/WebP/PDF/MP4/MOV and enforces media-specific size
 * and duration limits; failures are surfaced as readable messages.
 */
export async function uploadMediaAttachment(
  uri: string,
  name = 'attachment.jpg',
  type = 'image/jpeg',
  path = '/support/attachments/upload',
): Promise<string> {
  const form = new FormData();
  // React Native's FormData accepts this file-descriptor shape.
  form.append('file', { uri, name, type } as unknown as Blob);

  const token = await getToken();
  const res = await fetch(`${APP.apiBaseUrl.replace(/\/+$/, '')}${path}`, {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      // Content-Type omitted on purpose: fetch adds it with the boundary.
    },
    body: form,
  });

  if (!res.ok) {
    if (res.status === 413) throw new Error('That file is too large or too long.');
    if (res.status === 415) throw new Error('Only JPEG, PNG, WebP, MP4, MOV, or PDF files can be attached.');
    throw new Error('Could not upload that file.');
  }
  const data = (await res.json()) as { url: string };
  return data.url;
}

export const uploadTicketAttachment = (
  uri: string,
  name = 'attachment.jpg',
  type = 'image/jpeg',
) => uploadMediaAttachment(uri, name, type);

export const supportApi = {
  list: () => apiFetch<TicketListDto[]>('/support/tickets'),
  get: (id: string) => apiFetch<TicketDetailDto>(`/support/tickets/${id}`),
  create: (body: CreateTicketBody) =>
    apiFetch<TicketDetailDto>('/support/tickets', { method: 'POST', body }),
  reply: (id: string, body: string, attachments: string[] = []) =>
    apiFetch<TicketMessageCreateDto>(`/support/tickets/${id}/messages`, {
      method: 'POST',
      body: { body, attachments },
    }),
  rate: (id: string, rating: number) =>
    apiFetch<TicketDetailDto>(`/support/tickets/${id}/rate`, { method: 'POST', body: { rating } }),
};
